name = "BitSift"
uuid = "42faf63c-d721-40e7-8175-b035777ce658"
authors = ["Rupert Tombs <rupert.tombs@gmail.com>"]
version = "0.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
